services:
  - type: web
    name: weed-detection-website
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: INFERENCE_CONF
        value: "0.05"
      - key: INFERENCE_IMGSZ
        value: "512"
      - key: INFERENCE_DEVICE
        value: "cpu"
      - key: MAX_UPLOAD_MB
        value: "100"

